# This YAML configuration specifies a server with two volumes and two users
server:
  instance_type: t2.micro
  ami_type: amzn2
  architecture: x86_64
  root_device_type: ebs
  virtualization_type: hvm
  key_name: ec2-key-test
  min_count: 1
  max_count: 1
  volumes:
    - device: /dev/xvda
      size_gb: 10
      type: ext4
      mount: /
    - device: /dev/xvdf
      size_gb: 100
      type: xfs
      mount: /data
  users:
    - login: user1
      ssh_key: --user1 ssh public key goes here-- user1@localhost
    - login: user2
      ssh_key: --user2 ssh public key goes here-- user2@localhost
